version: "3.7"

services:
    python:
        build:
            context: .
            dockerfile: ./compose/production/python/Dockerfile
        env_file:
            - ./.envs/.integration_test/.py_env
            - ./.envs/.integration_test/.postgres
        command: /bin/bash -c "alembic upgrade head && /start"
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/ping/"]

    postgres:
        build:
            context: .
            dockerfile: ./compose/production/postgres/Dockerfile
        env_file:
            - ./.envs/.integration_test/.postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
            interval: 10s
            timeout: 5s
            retries: 5

    http_v1_integration:
        build:
            context: .
            dockerfile: ./integration_test/http/v1/Dockerfile
        env_file:
            - ./.envs/.integration_test/.py_env
            - ./.envs/.integration_test/.postgres
        depends_on:
            python:
                condition: service_healthy
